spring:
  application:
    name: auth-service
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL:jdbc:mysql://34.227.89.24:3306/auth_service?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8088
  servlet:
    context-path: /auth-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://174.129.84.80:8761/eureka

logging:
  level:
    com.hilltop: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:/home/ubuntu/log}